version: '3.7'

services:
  minecraft:
    build:
        context: ./build
        args:
            git_name: "Max Mustermann"
            git_email: "max.mustermann@musterdomain.de"
            version: "master"
    container_name: minecraft
    stop_grace_period: 2m
    depends_on: 
        - db
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 25565:25565
    volumes:
      - ./data/minecraft/configs/:/root/configs/
      - ./data/minecraft/world/:/root/world/
      - ./data/minecraft/world_nether/:/root/world_nether/
      - ./data/minecraft/world_the_end/:/root/world_the_end/
      - ./data/minecraft/plugins/:/root/plugins/
      - ./data/minecraft/configs/ops.json:/root/ops.json
      - ./data/minecraft/configs/whitelist.json:/root/whitelist.json
      - ./data/minecraft/configs/banned-ips.json:/root/banned-ips.json
      - ./data/minecraft/configs/banned-players.json:/root/banned-players.json
